# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ft2-ruby}
  s.version = "0.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Paul Duncan"]
  s.date = %q{2011-03-31}
  s.email = %q{pabs@pablotron.org}
  s.extensions = ["extconf.rb"]
  s.extra_rdoc_files = [
    "ChangeLog",
    "README",
    "TODO"
  ]
  s.files = [
    ".hgignore",
    "ChangeLog",
    "MANIFEST",
    "README",
    "Rakefile",
    "TODO",
    "VERSION",
    "examples/fonts/yudit.ttf",
    "examples/name_list.rb",
    "examples/test_ft2.rb",
    "extconf.rb",
    "ft2.c"
  ]
  s.homepage = %q{http://www.pablotron.org/}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.2}
  s.summary = %q{Ruby libraries to FreeType2}
  s.test_files = [
    "examples/name_list.rb",
    "examples/test_ft2.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

